table{
	thead{
		tr{
			th(class:'caption',colspan:2,'Uploaded to artifactory')
		}
		tr{
			th('Artifact')
			th('Status')
		}
	}
	tbody{
		ARTIFACTORY_UPLOAD.each{upload->
			tr{
				td{
					a(href:upload.publishUrl,upload.artifactName)
				}
				td(upload.status)
			}
		}
	}
}