table{
	thead{
		tr{
			th(class:'caption',colspan:4,'Previously deployed apps')
		}
		tr{
			th('App')
			th('Rev')
			th('Category')
			th('Build')
		}
	}
	tbody{
		CURRENTLY_DEPLOYED.each{build->
			tr{
				td(build.appname)
				td(build.svnrevisionnumber)
				td(build.category)
				td{
					a(href:build.jenkinsbuildurl,build.jenkinsbuildnumber)
				}
			}
		}
	}
}